name: lisence check

on:
  push:
    paths:
      - 'cron/requirements.txt'
      - '.github/workflows/lisence-check.yaml'

jobs:

  lisence-check:
    runs-on: ubuntu-22.04
    container:
      image: python:3.12.0a7-slim
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check lisence
        run: |
          cd cron
          chmod 775 ./*
          ls -al
          pip install --upgrade pip
          pip install pip-licenses
          pip-licenses --order=license
