name: lisence check

on:
  push:

jobs:
  lisence-check:
    runs-on: ubuntu-22.04
    container:
      image: python:3.12.0a7-slim
    steps:
      - name: check lisence
        run: |
          ls -al /_w
          ls -al /github/workflow
          ls -al /github/home
          pip install pip-licenses
          pip-licenses --order=license
