name: lisence check

on:
  push:

jobs:
  lisence-check:
    runs-on: ubuntu-22.04
    container:
      image: python:3.12.0a7-slim
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check lisence
        run: |
          ls -al /github
          ls -al /github/workflow
          ls -al /github/home
          ls -al /__w
          ls -al
          pip install pip-licenses
          pip-licenses --order=license
