name: lisence check

on:
  push:

jobs:
  lisence-check:
    runs-on: ubuntu-22.04
    container:
      image: python:3.12.0a7-slim
      volumes:
        - cron:/cron/
    steps:
      - name: check lisence
        run: |
          pip install pip-licenses
          pip-licenses --order=license
